project:
  type: book
  output-dir: docs

book:
  title: "Apuntes Prácticas de la asignatura de Bioestadística"
  subtitle: "Grado de Medicina - URJC. Primer curso"
  author: "Jesús Esteban Hernández y Jesús Martín Fernández"
  date: "4/9/2025"
  chapters:
  
    - index.qmd
    - part: "Instalación de R, RStudio y manejo básico."
      chapters: 
        - Prácticas_2025_26/Práctica_1/Práctica_1.qmd
        - Prácticas_2025_26/Práctica_1/Práctica_1_ejercicios.qmd
        - Prácticas_2025_26/Práctica_2/Práctica_2.qmd
        - Prácticas_2025_26/Práctica_2/Práctica_2_ejercicios.qmd
          
          
    # - Practicas_2024_25/Practica_3/Practica_3_pdf.qmd
    #   chapters:
    #     - Practicas_2024_25/Practica_3/Practica_3_ejercicios_pdf.qmd
    # 
    # - Practicas_2024_25/Practica_4/Practica_4.qmd
    #   chapters:
    #     - Practicas_2024_25/Practica_4/Practica_4_ejercicios.qmd

  


    # - Práctica 3_pdf.qmd 
    # - Práctica 4.qmd 
    # - Práctica 4_ejercicios.qmd 
    # - Práctica 5.qmd 
    # - Práctica 5_clase.qmd 
    # - Práctica 5_ejercicios.qmd 
    # - Práctica 6.qmd 
    # - Práctica 6_clase.qmd 
    # - Práctica 6_Ejercicios.qmd 
    # - Práctica 7.qmd 
    # - Práctica 7_ejercicios.qmd 
    # - Práctica 8.qmd 
    # - Práctica 8_clase.qmd 
    # - Práctica 8_ejercicios.qmd 
    # - Práctica 9.qmd 
    # - Práctica 9_clase.qmd 
    # - Práctica 9_ejercicios.qmd 
    # - Práctica 10.qmd
    # - Práctica 10_ejercicios.qmd 
    # - Práctica 11.qmd 
    # - Práctica 11_ejercicios.qmd 
    # - Práctica 12.qmd 
    # - Práctica 12_ejercicios.qmd 
    # - Práctica 13.qmd 
    # - Práctica 13_ejercicios.qmd 
    # - Práctica 14.qmd 
    # - Práctica 14_ejercicios.qmd 
    - references.qmd

lang: es
bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrbook
