name: Deploy Quarto book to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3️⃣ Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 4️⃣ Renderizar libro
      - name: Render book
        run: quarto render
        shell: bash  # opcional, Ubuntu usa bash por defecto

      # 5️⃣ Subir artefacto _book
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_book'

      # 6️⃣ Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
